Add class names to expose library elements for CSS styling
nishanbajracharya/react-virtualized-listview pull request #5
Opened 2018-08-27 11:05 UTC by rabingaire

closes #1

2018-08-27 12:14 UTC, nishanbajracharya requested changes

2018-08-27 12:14 UTC, nishanbajracharya commented on src/index.js
> +      className={this.props.className ? this.props.className : ''}
We can just keep the class name as follows:
```js
className={this.props.className}
```
If the prop is not set, the value will be `undefined` and the className key will not be created. However if we use the ternary check, an empty classname will be set when classname prop is not passed.

2018-08-27 12:14 UTC, nishanbajracharya commented on src/index.js
> +    return this.props.className ? {} : { height: '300px', width: '600px' };
Let's remove the redundant `return` and braces here.
```js
getDefaultHeightWidth = () => this.props.className ? {} : { height: '300px', width: '600px' };
```

Also why are we setting arbitrary values in the `height` and `width` props? Let's set them to `100%`. This way, the component height and width will default to using the full dimensions of its parent.

The user has to be able to use the component with as little configuration as possible. So setting a container width and height in the classname that they have to also set would be quite a lot of initial work.

2018-08-27 12:14 UTC, nishanbajracharya commented on src/index.js
> +  className: PropTypes.string
Length rule requirement here.

2018-08-27 12:14 UTC, nishanbajracharya commented on src/index.js
> +    width
Length rule requirement here.

2018-08-27 14:20 UTC, rabingaire commented on src/index.js
> +  className: PropTypes.string
I didn't get what you meant here?

2018-08-27 14:20 UTC, rabingaire commented on src/index.js
> +    width
I didn't get what you meant here?

2018-08-28 04:28 UTC, nishanbajracharya commented on src/index.js
> +  className: PropTypes.string
Order the proptypes based on the length of the line in ascending order. So the `className` prop needs to be third in this list. This is just a code formatting preference and doesn't affect the functionality of the code.

2018-08-28 04:28 UTC, nishanbajracharya commented on src/index.js
> +    width
Same here.

2018-08-31 07:00 UTC, nishanbajracharya approved these changes

2018-08-31 07:01 UTC, merged